rhblind/drf-haystack

- drf_haystack/filters.py
- tests/test_filters.py
This PR allows the views to accept field lookups in the search query parameters.
e.g. `https://host.com/api/v1/model/search/?field__contains=foobar`
Tests included
> allow field lookups in query filters

- drf_haystack/serializers.py
- tests/test_serializers.py
This fixes #16.  It includes a test for using the `exclude` attribute
> Fix HaystackSerializer 'fields' and 'exclude' attributes

- docs/advanced_usage.rst
- drf_haystack/fields.py
- drf_haystack/filters.py
- drf_haystack/serializers.py
- tests/mockapp/fixtures/mockpet.json
- tests/mockapp/migrations/0003_mockpet.py
- tests/mockapp/migrations/0004_load_fixtures.py
- tests/mockapp/models.py
- tests/mockapp/search_indexes.py
- tests/mockapp/templates/search/indexes/mockapp/mockpet_text.txt
- tests/test_filters.py
- tests/test_serializers.py
Okay, this ended up being more involved than I originally thought, but here's a PR with enhanced support for using multiple indexes.  I'll describe the following major pieces below:
* Automatic Multiple Index Field Handling
* Ability to Use Multiple Serializers
* Serializer Mixin
* Miscellaneous
The original problem that needed to be solved was that if you used multiple indexes that had overlapping field names, only one field would be used.  If they happened to be different field types, that would be a big problem.
The code in this PR internally modifies the field names to associate them with a specific index.  Let's say we have the following setup:
```python
class Index1(indexes.searchIndex, indexes.Indexable):
text = indexes.CharField(document=True, use_template=True)
my_field = …
```
> Fix multiple index field support

- docs/advanced_usage.rst
- drf_haystack/filters.py
Added `BaseHaystackGEOSpatialFilter` with `point_field` (string) which points to the `LocationField` in the index. Default behaviour of `HaystackGEOSpatialFilter` has been left intact. Docs updated.
> more flexible HaystackGEOSpatialFilter

- drf_haystack/serializers.py
- tests/test_serializers.py
The logic around `ignore_fields` was wrong. This has been fixed, cleaned up a bit and some testing for this is added to avoid future problems.
> Proper handling of ignore_fields

- drf_haystack/constants.py
- drf_haystack/filters.py
- drf_haystack/query.py
- drf_haystack/serializers.py
- tests/settings.py
- tests/test_filters.py
- tests/test_serializers.py
Replacement for #41
I think the filters and query related logic could be even more refactored. Move the remaining validation logic somewhere else so that they’re easier to test. Beyond the Meta though I couldn’t come up with a consistent way to do it. Food for thought.
> Moved filter query building logic and added meta classes to handle integrity of serializers

- README.md
- docs/advanced_usage.rst
- docs/conf.py
- docs/index.rst
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs link for their .org -> .io migration for hosted projects

- drf_haystack/serializers.py
- tests/test_serializers.py
The narrow_url value is now an absolute URL rather than simply the path component.
Fixes #56
> Using an absolute URL for the narrow_url field

- docs/07_faceting.rst
- docs/10_tips_n_tricks.rst
- drf_haystack/mixins.py
- drf_haystack/serializers.py
Added these two features
- URL param can be defined in the view itself. We need to define attribute `facet_query_params_text` on intended view to  replace ``selected_facets`` query text in urls.
- Made MoreLikeThisMixin and FacetMixin more usable by removing dependency of viewset. `MoreLikeThisBaseMixin` and `FacetBaseMixin` can be used in regular views.
> Added query param text & made MLT/Faceting mixins more usable

- docs/09_multiple_indexes.rst
- drf_haystack/serializers.py
These warnings can be somewhat noisy when the override behavior is expected. The warning has been removed, and a note added to the documentation.
Fixes #77
> Removed field override warning

- drf_haystack/serializers.py
With django-rest-framework 3.5 Hyperlink 'name' as made 'lazy',
changing the name argument in the process.
If we call it without a keyword, it should work in both old and new drf
verions.
> drf 3.5, fix TypeError

- drf_haystack/generics.py
Fix for bug in get_queryset() where the queryset attribute is set, but evaluates to empty list, causing ELSE to be triggered
> (fix) queryset attr evaluates to False when empty

- drf_haystack/generics.py
This was causing the `queryset` attribute to be ignored. (#90)
> Corrected what seemed like the omission of a "not" in HaystackGenericAPIView

- docs/03_geospatial.rst
- drf_haystack/constants.py
- drf_haystack/query.py
It allow to change the default argument 'from' to anoter keywork,
since it may cause some trouble when using Serializers to validate
the query parameters, as this is a python reserved keyword.
> Add DRF_HAYSTACK_SPATIAL_QUERY_PARAM to constants

- drf_haystack/query.py
I came across the following error:
```
File "/usr/local/pythons/current/lib/python3.4/site-packages/drf_haystack/generics.py", line 98, in filter_queryset
queryset = super(HaystackGenericAPIView, self).filter_queryset(queryset)
File "/usr/local/pythons/current/lib/python3.4/site-packages/rest_framework/generics.py", line 152, in filter_queryset
queryset = backend().filter_queryset(self.request, queryset, self)
File "/usr/local/pythons/current/lib/python3.4/site-packages/drf_haystack/filters.py", line 58, in filter_queryset
applicable_filters, applicable_exclusions = self.build_filters(view, filters=self.get_request_filters(request))
File "/usr/local/pythons/current/lib/python3.4/site-packages/drf_haystack/filters.py", line 45, in build_filters
return query_builder.build_query(**(filters …
```
> safe attribute access

- README.md
(AN: my misinterpretation of this one line cost me at least 4 hours in debugging time. I'd love to spare others from my fate!)
By calling the serializer PersonSerializer, there's an implicit assumption made by the user that this is the same serializer that should govern the list/detail views (if they exist) of the Person model, but this clearly isn't the case.
By changing the name of the serializer to PersonSearchSerializer (as a tutorial I found did), it becomes immediately clear that the Haystack serializer is not supposed to be the same serializer as the serializer for the model throughout the rest of the API.
> Clarify serializer example

- drf_haystack/serializers.py
The `rest_framework.pagination._get_count` function [was removed](https://github.com/encode/django-rest-framework/commit/a7e2a7bfcdf9d10dd3f5c1061245f34a8e5227b6) in DRF 3.8. This patch moves this method to the `HaystackFacetSerializer` class.
> Fix the `_get_count` for DRF 3.8

- drf_haystack/serializers.py
Adds support for SlugField by removing the `allow_unicode` parameter in the haystack field
> feat: support SlugField

- drf_haystack/serializers.py
- tests/test_serializers.py
This is a refresh of PR #118, updated with the latest project changes.  It still fixes #99 and modifies tests to confirm the value of declared fields, not just their presence
> fix declared fields (#99)

- docs/conf.py
- docs/index.rst
- drf_haystack/__init__.py
- drf_haystack/serializers.py
- tests/test_serializers.py
- Fixed 139 - Serializers must now use `serializers.SerializerMethodField` for overriding fields.
- Updated docs - Links to new repository owner
> drf-haystack-139

- .travis.yml
- Pipfile
- README.md
- docs/index.rst
- docs/rtd_requirements.txt
- drf_haystack/mixins.py
- setup.py
- tox.ini
Support the latest version of DRF (3.10.x)
DjangoRestFramework dropped Python2 support in 3.10.0 (https://www.django-rest-framework.org/community/release-notes/#3100).
Since Python2 end of life is January  2020, I've also removed all references to Python2.7.
> Add support for DjangoRestFramework 3.10.x

- drf_haystack/serializers.py
1.  Handle case where data of the field to be highlighted is None,
causing highlight method to fail since it expects data to be of string type. Fixes #155 
2. Taking out the extraction of terms from the request into a method of its own,
namely `get_terms` so that its easier to override it with a custom implementation,
adds to separation of concerns.
> Handle case where data to be highlighted is None, and minor refactoring

- docs/index.rst
- drf_haystack/__init__.py
- setup.py
The code was already 99% compatible with DRF 3.12.x since the Pipfile  support DRF `">=3.7.0,<3.13"` 
However, djangorestframework version support wasn't changed in the setup.py file
> Support DRF 3.12.x

- drf_haystack/filters.py
- drf_haystack/query.py
Also rename field_queries to param_queries to prevent confusion (filtering is done per param, not per field perse).
Fixes #92
> Add 'default_same_param_operator' to the FilterQueryBackend

- Pipfile
- docs/index.rst
- docs/rtd_requirements.txt
- drf_haystack/__init__.py
- drf_haystack/serializers.py
- setup.py
Support Django-Haystack 3.1.0
During their last deployment/release, the Django-Haystack has messed up their 3.0 version by overriding their wheel file with the 3.1.0 content.
By supporting django-haystack 3.1.0 ... there's no need to ask them to fix this annoying issue ( drf-haystack 1.8.10 is not compatible with django-haystack 3.1.0 )
> Support Django-Haystack 3.1.0

- docs/09_multiple_indexes.rst
According to v1.8.6 and #139 fields should be changed from serializers.IntegerField()/CharField()... to SerializerMethodField(). Also in get__<...> functions should be added instance arg couse of the DRF documentation.
I just read documentation without looking at the Chanel log and maybe if hadn't looked at the Chanel log after I would spend much more time searching what's wrong.
Please merge this request to avoid similar situations in the future. :+1:
> Update dosc declared fields

- docs/07_faceting.rst
Spotted a typo while reading the doc, fixed it.
The two trailing whitespaces has been removed by my editor, hope that's ok to clean this too.
While I'm here, happens than those 3 errors were spotted by `sphinx-lint`, you may use it:
```
$ sphinx-lint docs/
docs/07_faceting.rst:221: role missing colon before first backtick ( :class:drf_haystack.filters.HaystackFacetFilter`). (missing-colon-in-role)
docs/07_faceting.rst:244: trailing whitespace (trailing-whitespace)
docs/07_faceting.rst:245: trailing whitespace (trailing-whitespace)
```
> doc: Fixed a missing backtick.

- drf_haystack/query.py
`applicable_filters` and `applicable_exclusions` are of type `type(self.view.query_object)`. For  better consistency, we should return an empty query object instead of an empty list.
> Return an empty query object instead of an empty list when no filter is passed

- drf_haystack/serializers.py
This allows to get the full id of a content, for example:
```
[
{
"id": "organization_projects.project.2",
"category": "Software",
"languages": "Python",
"premium": true
}
]
```
> add "id" as an optional value of the serializer fields returning the haystack internal id
